/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DualMarketRouteImport } from './routes/dual-market'
import { Route as IndexRouteImport } from './routes/index'

const DualMarketRoute = DualMarketRouteImport.update({
  id: '/dual-market',
  path: '/dual-market',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dual-market': typeof DualMarketRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dual-market': typeof DualMarketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dual-market': typeof DualMarketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dual-market'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dual-market'
  id: '__root__' | '/' | '/dual-market'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DualMarketRoute: typeof DualMarketRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dual-market': {
      id: '/dual-market'
      path: '/dual-market'
      fullPath: '/dual-market'
      preLoaderRoute: typeof DualMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DualMarketRoute: DualMarketRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
