/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DualMarketRouteImport } from './routes/dual-market'
import { Route as AiPicksRouteImport } from './routes/ai-picks'
import { Route as IndexRouteImport } from './routes/index'

const DualMarketRoute = DualMarketRouteImport.update({
  id: '/dual-market',
  path: '/dual-market',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPicksRoute = AiPicksRouteImport.update({
  id: '/ai-picks',
  path: '/ai-picks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-picks': typeof AiPicksRoute
  '/dual-market': typeof DualMarketRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-picks': typeof AiPicksRoute
  '/dual-market': typeof DualMarketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-picks': typeof AiPicksRoute
  '/dual-market': typeof DualMarketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-picks' | '/dual-market'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-picks' | '/dual-market'
  id: '__root__' | '/' | '/ai-picks' | '/dual-market'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiPicksRoute: typeof AiPicksRoute
  DualMarketRoute: typeof DualMarketRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dual-market': {
      id: '/dual-market'
      path: '/dual-market'
      fullPath: '/dual-market'
      preLoaderRoute: typeof DualMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-picks': {
      id: '/ai-picks'
      path: '/ai-picks'
      fullPath: '/ai-picks'
      preLoaderRoute: typeof AiPicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiPicksRoute: AiPicksRoute,
  DualMarketRoute: DualMarketRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
